/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentcar.interfacegrafica;

import rentcar.entidade.Cliente;
import rentcar.entidade.Carro;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author rodrigo
 */

public class TelaEfetuarVenda extends javax.swing.JFrame {

    public TelaEfetuarVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTNomeCarro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTDesconto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Efetuar Venda");

        jLabel1.setText("Nome do Cliente");

        jLabel3.setText("Nome do Carro");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Procurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Desconto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                            .addComponent(jTNomeCarro)
                            .addComponent(jTNomeCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTDesconto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNomeCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    
    ArrayList <Cliente> clientes = new ArrayList <>();
    ArrayList <Carro> carros = new ArrayList <>();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            if((jTNomeCliente.getText().equals(""))||jTNomeCarro.getText().equals("") || jTDesconto.getText().equals("")) {
                throw new CampoNullExc("Campo em branco, por favor Preencha");
            }else {
                //Ler
                try {
                    FileInputStream arquivoLeitura = new FileInputStream("/home/ProjetoFinal/db/cadCliente.dat");
                    ObjectInputStream objLeitura = new ObjectInputStream(arquivoLeitura);
                    try{
                        while(true){
                            clientes.add((Cliente)objLeitura.readObject());
                        }
                    }catch(IOException e) {
                        System.out.println("Fim Arquivo");
                    }
                    objLeitura.close();
                    arquivoLeitura.close();
                } catch (ClassNotFoundException | IOException ex) {
                }
                 //Ler
                try {
                    FileInputStream arquivoLeitura = new FileInputStream("/home/ProjetoFinal/db/cadCarro.dat");
                    ObjectInputStream objLeitura = new ObjectInputStream(arquivoLeitura);
                    try{
                        while(true){
                            carros.add((Carro)objLeitura.readObject());
                        }
                    }catch(IOException e) {
                        System.out.println("Fim Arquivo");
                    }
                    objLeitura.close();
                    arquivoLeitura.close();
                } catch (ClassNotFoundException | IOException ex) {
                }
                int flag1 = 0, flag2 = 0, flag3 = 0, flag4 = 0, i, j;
                for(i=0;i<clientes.size();i++) {
                    if(clientes.get(i).getNome().equals(jTNomeCliente.getText())) {
                        flag4 = Integer.parseInt(jTDesconto.getText());
                        if(flag4 > 0 && flag4 <= 5000){ //Desconto máximo 5000
                            flag1 = 1;
                            break;
                        }
                    }
                    else flag1 = 0;
                    
                    
                }
                for(j= 0;j<carros.size();j++) {
                    if(carros.get(j).getNome().equals(jTNomeCarro.getText())) {
                        if((carros.get(j).getnVendidos()<carros.get(j).getnTotal())){
                            flag3 = 1;
                        }
                        flag2 = 1;
                        break;
                    }
                    else flag2 = 0;
                }

                String str1, str2, str3, str;
                if(flag1==1) {
                    str1 = ("Cliente Encontrado\n");
                }else str1 =("Cliente Não Encontrado\n");
                
                if(flag1==1 && flag4!=0) {
                    str3 = ("Desconto Válido\n");
                }else str3 =("Desconto Inválido\n");
                
                if(flag2==1 && flag3==1) {
                    str2 = ("Carro Encontrado\n");
                }else if(flag2==1 && flag3==0) {
                    str2 = ("Sem veiculos disponiveis\n");
                }
                else str2 = ("Carro Não Encontrado\n");
                str =(str1+str2+str3);
                if(flag1==1 && (flag2==1 && flag3==1 && flag4!=0)) {
                    clientes.get(i).setVendido(carros.get(j));
                    clientes.get(i).setValorDesconto(flag4);
                    carros.get(j).setnVendidos(carros.get(j).getnVendidos()+1);
                    clientes.get(i).setTotalPagar(carros.get(j).getPreco()-Double.parseDouble(jTDesconto.getText()));
                    carros.get(i).setnTotal(carros.get(i).getnTotal()-1);
                    jTextArea1.setText(str+"Venda realizada\nTotal a pagar: "+clientes.get(i).getTotalPagar());
                }else jTextArea1.setText(str+"Venda não realizada");

                //Gravar
                FileOutputStream arquivoGrav = null;
                try {
                    arquivoGrav = new FileOutputStream("/home/ProjetoFinal/db/cadCliente.dat");
                    ObjectOutputStream objGravar = new ObjectOutputStream(arquivoGrav);
                    for(i=0; i<clientes.size();i++) {
                        objGravar.writeObject(clientes.get(i));
                    }
                    objGravar.flush();
                    objGravar.close();
                    arquivoGrav.flush();
                    arquivoGrav.close();
                } catch (IOException ex) {
                    System.out.println("Erro ao gravar");
                }

                //Gravar
                arquivoGrav = null;
                try {
                    arquivoGrav = new FileOutputStream("/home/ProjetoFinal/db/cadCarro.dat");
                    ObjectOutputStream objGravar = new ObjectOutputStream(arquivoGrav);
                    for( i=0; i<carros.size();i++) {
                        objGravar.writeObject(carros.get(i));
                    }
                    objGravar.flush();
                    objGravar.close();
                    arquivoGrav.flush();
                    arquivoGrav.close();
                } catch (IOException ex) {
                    System.out.println("Erro ao gravar");
                }

                clientes.clear();
                carros.clear();
            }
        }catch(CampoNullExc x) {
                    JOptionPane.showMessageDialog(null, ""+x.getMessage());
            }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        setVisible(false);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEfetuarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEfetuarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTNomeCarro;
    private javax.swing.JTextField jTNomeCliente;
    private javax.swing.JTextField jTDesconto;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
